local map = vim.keymap.set

map("i", "<C-b>", "<ESC>^i", { desc = "move beginning of line" })
map("i", "<C-e>", "<End>", { desc = "move end of line" })
map("i", "<C-h>", "<Left>", { desc = "move left" })
map("i", "<C-l>", "<Right>", { desc = "move right" })
map("i", "<C-j>", "<Down>", { desc = "move down" })
map("i", "<C-k>", "<Up>", { desc = "move up" })

map("n", "<C-h>", "<C-w>h", { desc = "switch window left" })
map("n", "<C-l>", "<C-w>l", { desc = "switch window right" })
map("n", "<C-j>", "<C-w>j", { desc = "switch window down" })
map("n", "<C-k>", "<C-w>k", { desc = "switch window up" })

map("n", "<Esc>", "<CMD>noh<CR>", { desc = "clear highlights", noremap = true, nowait = true })
map("n", "<leader>/", "gcc", { desc = "toggle comment", remap = true })
map("v", "<leader>/", "gc", { desc = "toggle comment", remap = true })
map("n", "<leader>n", function()
  vim.wo.number = not vim.wo.number
end, { desc = "toggle line number" })
map("n", "<leader>fd", "za", { desc = "fold toggle", nowait = true })

map("n", "<leader>tt", "<CMD>tabnew<CR>", { desc = "tab new" })
map("n", "<leader>tc", "<CMD>tabclose<CR>", { desc = "tab close" })
map("n", "<leader>tn", "<CMD>tabn<CR>", { desc = "tab next", noremap = true })
map("n", "<leader>tp", "<CMD>tabp<CR>", { desc = "tab prev", noremap = true })

map("n", "<leader>b", "<CMD>enew<CR>", { desc = "buffer new" })
map("n", "<tab>", function()
  require("if.ui.bufline").next()
end, { desc = "buffer goto next" })
map("n", "<S-tab>", function()
  require("if.ui.bufline").prev()
end, { desc = "buffer goto prev" })
map("n", "<leader>x", function()
  require("if.ui.bufline").close_buf()
end, { desc = "buffer close" })

map("n", "K", vim.lsp.buf.hover, { desc = "LSP hover", nowait = true })
map("n", "gd", vim.lsp.buf.definition, { desc = "LSP goto definition", nowait = true, noremap = true })
map("n", "<leader>ca", vim.lsp.buf.code_action, { desc = "LSP code action", nowait = true })
map("n", "<leader>rr", vim.lsp.buf.rename, { desc = "LSP rename", nowait = true })
map("n", "<leader>ds", vim.diagnostic.setloclist, { desc = "LSP diagnostic loclist" })
map("n", "<leader>gn", function()
  vim.diagnostic.jump { count = 1, float = true }
end, { desc = "LSP diagnostic next", nowait = true })
map("n", "<leader>gp", function()
  vim.diagnostic.jump { count = -1, float = true }
end, { desc = "LSP diagnostic prev", nowait = true })
map("n", "<leader>th", function()
  vim.lsp.inlay_hint.enable(not vim.lsp.inlay_hint.is_enabled())
end, { desc = "toggle inlay hints", noremap = true })
map("n", "<leader>fm", function()
  require("conform").format { async = true, lsp_format = "fallback" }
end, { desc = "LSP formatting" })

map("n", "<leader>ff", function()
  Snacks.picker.files()
end, { desc = "find files" })
map("n", "<leader>fo", function()
  Snacks.picker.recent()
end, { desc = "find recent files" })
map("n", "<leader>fa", function()
  Snacks.picker.files { hidden = true, ignored = true }
end, { desc = "find all files" })
map("n", "<leader>fw", function()
  Snacks.picker.grep()
end, { desc = "live grep" })
map("n", "<leader>fs", function()
  Snacks.picker.grep { hidden = true, ignored = true }
end, { desc = "live grep all" })
map("n", "<leader>fz", function()
  Snacks.picker.lines()
end, { desc = "find in current buffer" })
map("n", "<leader>fb", function()
  Snacks.picker.buffers()
end, { desc = "find buffers" })
map("n", "<leader>fh", function()
  Snacks.picker.help()
end, { desc = "help pages" })
map("n", "<leader>fq", function()
  Snacks.picker.qflist()
end, { desc = "quickfix list" })
map("n", "<leader>ws", function()
  Snacks.picker.projects()
end, { desc = "projects" })
map("n", "<leader>lo", function()
  Snacks.picker.lsp_symbols()
end, { desc = "LSP symbols", nowait = true })
map("n", "grr", function()
  Snacks.picker.lsp_references()
end, { desc = "LSP references", nowait = true })

map("n", "<leader>gg", function()
  Snacks.lazygit()
end, { desc = "open lazygit", nowait = true })
map("n", "<leader>gs", function()
  Snacks.picker.git_status()
end, { desc = "git status" })
map("n", "<leader>gb", function()
  Snacks.picker.git_branches()
end, { desc = "git branches" })
map("n", "<leader>gl", function()
  Snacks.picker.git_log()
end, { desc = "git log" })
map(
  "n",
  "<leader>cb",
  "<CMD>Gitsigns toggle_current_line_blame<CR>",
  { desc = "toggle git blame line", nowait = true, noremap = true }
)
map("n", "<leader>bl", "<CMD>Gitsigns blame_line<CR>", { desc = "git blame line", nowait = true, noremap = true })

map("n", "<C-n>", function()
  Snacks.explorer()
end, { desc = "toggle explorer" })
map("n", "<leader>e", function()
  Snacks.explorer()
end, { desc = "focus explorer" })
map({ "n", "t" }, "<A-i>", function()
  Snacks.terminal.toggle(nil, { win = { position = "float" } })
end, { desc = "toggle float terminal" })
map({ "n", "t" }, "<A-h>", function()
  Snacks.terminal.toggle(nil, { win = { position = "bottom", height = 0.3 } })
end, { desc = "toggle horizontal terminal" })
map({ "n", "t" }, "<A-v>", function()
  Snacks.terminal.toggle(nil, { win = { position = "right", width = 0.2 } })
end, { desc = "toggle vertical terminal" })
map("t", "<C-x>", "<C-\\><C-N>", { desc = "exit terminal mode" })

map("n", "<leader>ql", "<CMD>copen<CR>", { desc = "open quickfix list" })
map("n", "<leader>fr", function()
  local idx = vim.fn.line "."
  local qf = vim.fn.getqflist()
  table.remove(qf, idx)
  vim.fn.setqflist({}, "r", { items = qf })
end, { desc = "remove quickfix item under cursor" })

map("n", "<leader>dn", "<CMD>NoiceDismiss<CR>", { desc = "dismiss notifications", nowait = true })
